// <auto-generated />
using System;
using KayCare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KayCare.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328223714_AddPartialDispense")]
    partial class AddPartialDispense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KayCare.Core.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Scheduled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "DoctorUserId", "ScheduledAt");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("KayCare.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Bill", b =>
                {
                    b.Property<Guid>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("BalanceDue")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(12,2)")
                        .HasComputedColumnSql("[TotalAmount] - [PaidAmount]", true);

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("BillId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "BillNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("KayCare.Core.Entities.BillItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(12,2)")
                        .HasComputedColumnSql("[Quantity] * [UnitPrice]", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Consultation", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssessmentNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("DoctorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HeartRateBPM")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("ObjectiveNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OxygenSaturationPct")
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryDiagnosisCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryDiagnosisDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecondaryDiagnoses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("SubjectiveNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ConsultationId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "PatientId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("KayCare.Core.Entities.DispenseEvent", b =>
                {
                    b.Property<Guid>("DispenseEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("DispensedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DispensedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DispenseEventId");

                    b.HasIndex("DispensedByUserId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("TenantId", "PrescriptionId");

                    b.ToTable("DispenseEvents");
                });

            modelBuilder.Entity("KayCare.Core.Entities.DispenseEventItem", b =>
                {
                    b.Property<Guid>("DispenseEventItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("DispenseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrescriptionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityDispensed")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DispenseEventItemId");

                    b.HasIndex("DispenseEventId");

                    b.HasIndex("PrescriptionItemId");

                    b.ToTable("DispenseEventItems");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabObservation", b =>
                {
                    b.Property<Guid>("LabObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AbnormalFlag")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("LabResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Units")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LabObservationId");

                    b.HasIndex("LabResultId");

                    b.HasIndex("TenantId", "LabResultId");

                    b.ToTable("LabObservations");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrder", b =>
                {
                    b.Property<Guid>("LabOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrderingDoctorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("LabOrderId");

                    b.HasIndex("BillId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("OrderingDoctorUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("LabOrders");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrderItem", b =>
                {
                    b.Property<Guid>("LabOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("bit");

                    b.Property<Guid>("LabOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LabResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabTestCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManualResult")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ManualResultFlag")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManualResultNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ManualResultReferenceRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManualResultUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResultedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SampleReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TatHours")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LabOrderItemId");

                    b.HasIndex("LabOrderId");

                    b.HasIndex("LabTestCatalogId");

                    b.HasIndex("TenantId", "AccessionNumber")
                        .IsUnique()
                        .HasFilter("[AccessionNumber] IS NOT NULL");

                    b.ToTable("LabOrderItems");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabResult", b =>
                {
                    b.Property<Guid>("LabResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("LabOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderingDoctorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawHl7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Received");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("LabResultId");

                    b.HasIndex("LabOrderItemId")
                        .IsUnique()
                        .HasFilter("[LabOrderItemId] IS NOT NULL");

                    b.HasIndex("OrderingDoctorUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "AccessionNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PatientId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabTestCatalog", b =>
                {
                    b.Property<Guid>("LabTestCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DefaultReferenceRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("bit");

                    b.Property<int>("TatHours")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LabTestCatalogId");

                    b.HasIndex("TestCode")
                        .IsUnique();

                    b.ToTable("LabTestCatalog");

                    b.HasData(
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000001"),
                            Department = "Haematology",
                            InstrumentType = "DxH560",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 2,
                            TestCode = "FBC",
                            TestName = "Full Blood Count"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000002"),
                            DefaultReferenceRange = "0-20",
                            DefaultUnit = "mm/hr",
                            Department = "Haematology",
                            InstrumentType = "DxH560",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 2,
                            TestCode = "ESR",
                            TestName = "Erythrocyte Sedimentation Rate"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000003"),
                            Department = "Haematology",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 4,
                            TestCode = "MPS",
                            TestName = "Blood Film for Malaria Parasite Screen"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000004"),
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 3,
                            TestCode = "BUE",
                            TestName = "Blood Urea and Electrolytes & Creatinine"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000005"),
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 3,
                            TestCode = "LFT",
                            TestName = "Liver Function Tests"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000006"),
                            DefaultReferenceRange = "0.70-1.10",
                            DefaultUnit = "mmol/L",
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 3,
                            TestCode = "MAGNESIUM",
                            TestName = "Magnesium"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000007"),
                            DefaultReferenceRange = "2.10-2.55",
                            DefaultUnit = "mmol/L",
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 3,
                            TestCode = "CALCIUM",
                            TestName = "Calcium"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000008"),
                            DefaultReferenceRange = "3.9-5.6",
                            DefaultUnit = "mmol/L",
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 1,
                            TestCode = "FBG",
                            TestName = "Fasting Blood Glucose"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000009"),
                            DefaultReferenceRange = "3.9-7.8",
                            DefaultUnit = "mmol/L",
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 1,
                            TestCode = "RBG",
                            TestName = "Random Blood Glucose"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000010"),
                            Department = "Chemistry",
                            InstrumentType = "DxC500",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 3,
                            TestCode = "LIPID",
                            TestName = "Lipid Profile"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000011"),
                            Department = "Immunology",
                            InstrumentType = "CobasE411",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 4,
                            TestCode = "TFT",
                            TestName = "Thyroid Function Tests (TSH, T3, T4)"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000012"),
                            DefaultReferenceRange = "197-866",
                            DefaultUnit = "pg/mL",
                            Department = "Immunology",
                            InstrumentType = "CobasE411",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 4,
                            TestCode = "VIT_B12",
                            TestName = "Vitamin B12"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000013"),
                            DefaultReferenceRange = "4.6-18.7",
                            DefaultUnit = "ng/mL",
                            Department = "Immunology",
                            InstrumentType = "CobasE411",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 4,
                            TestCode = "FOLATE",
                            TestName = "Folate / Folic Acid"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000014"),
                            DefaultReferenceRange = "4.0-5.6",
                            DefaultUnit = "%",
                            Department = "Immunology",
                            InstrumentType = "CobasE411",
                            IsActive = true,
                            IsManualEntry = false,
                            TatHours = 4,
                            TestCode = "HBA1C",
                            TestName = "Glycosylated Haemoglobin (HbA1c)"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000015"),
                            Department = "Serology",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 6,
                            TestCode = "TYPHOID",
                            TestName = "Typhoid IgG / IgM"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000016"),
                            Department = "Serology",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 6,
                            TestCode = "WIDAL",
                            TestName = "Widal Test"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000017"),
                            Department = "Urinalysis",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 2,
                            TestCode = "URINE_RE",
                            TestName = "Urine Routine Examination"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000018"),
                            Department = "Serology",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 3,
                            TestCode = "HBsAg",
                            TestName = "Hepatitis B Surface Antigen"
                        },
                        new
                        {
                            LabTestCatalogId = new Guid("10000001-0000-0000-0000-000000000019"),
                            Department = "Serology",
                            IsActive = true,
                            IsManualEntry = true,
                            TatHours = 1,
                            TestCode = "HIV",
                            TestName = "HIV Screening Test"
                        });
                });

            modelBuilder.Entity("KayCare.Core.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("GH");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("RegisteredAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasAllergies")
                        .HasColumnType("bit");

                    b.Property<bool>("HasChronicConditions")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceGroupNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsuranceProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PatientId");

                    b.HasIndex("TenantId", "LastName");

                    b.HasIndex("TenantId", "MedicalRecordNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PatientAllergy", b =>
                {
                    b.Property<Guid>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AllergenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AllergyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reaction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AllergyId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId", "PatientId");

                    b.ToTable("PatientAllergies");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PatientDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Other");

                    b.Property<Guid?>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("TenantId", "Category");

                    b.HasIndex("TenantId", "PatientId");

                    b.ToTable("PatientDocuments");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("TenantId", "BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Prescription", b =>
                {
                    b.Property<Guid>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DispensedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrescribedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("DispensedByUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescribedByUserId");

                    b.HasIndex("TenantId", "ConsultationId");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsControlledSubstance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullyDispensed")
                        .HasColumnType("bit");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispensed")
                        .HasColumnType("int");

                    b.Property<int>("Refills")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId", "CreatedByUserId");

                    b.HasIndex("TenantId", "IsShared");

                    b.ToTable("PrescriptionTemplates");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionTemplateItem", b =>
                {
                    b.Property<Guid>("TemplateItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsControlledSubstance")
                        .HasColumnType("bit");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Refills")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateItemId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PrescriptionTemplateItems");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Platform-level administrator",
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Hospital administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Licensed physician",
                            RoleName = "Doctor"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Nursing staff",
                            RoleName = "Nurse"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Front desk / patient registration",
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Pharmacy staff",
                            RoleName = "Pharmacist"
                        });
                });

            modelBuilder.Entity("KayCare.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<int>("StorageQuotaGB")
                        .HasColumnType("int");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("standard");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TenantId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("KayCare.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Appointment", b =>
                {
                    b.HasOne("KayCare.Core.Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Bill", b =>
                {
                    b.HasOne("KayCare.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.BillItem", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Consultation", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.DispenseEvent", b =>
                {
                    b.HasOne("KayCare.Core.Entities.User", "DispensedBy")
                        .WithMany()
                        .HasForeignKey("DispensedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Prescription", "Prescription")
                        .WithMany("DispenseEvents")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispensedBy");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("KayCare.Core.Entities.DispenseEventItem", b =>
                {
                    b.HasOne("KayCare.Core.Entities.DispenseEvent", "Event")
                        .WithMany("Items")
                        .HasForeignKey("DispenseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.PrescriptionItem", "PrescriptionItem")
                        .WithMany()
                        .HasForeignKey("PrescriptionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("PrescriptionItem");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabObservation", b =>
                {
                    b.HasOne("KayCare.Core.Entities.LabResult", "LabResult")
                        .WithMany("Observations")
                        .HasForeignKey("LabResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabResult");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrder", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KayCare.Core.Entities.Consultation", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KayCare.Core.Entities.User", "OrderingDoctor")
                        .WithMany()
                        .HasForeignKey("OrderingDoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Consultation");

                    b.Navigation("OrderingDoctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrderItem", b =>
                {
                    b.HasOne("KayCare.Core.Entities.LabOrder", "LabOrder")
                        .WithMany("Items")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.LabTestCatalog", "LabTestCatalog")
                        .WithMany()
                        .HasForeignKey("LabTestCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabOrder");

                    b.Navigation("LabTestCatalog");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabResult", b =>
                {
                    b.HasOne("KayCare.Core.Entities.LabOrderItem", "LabOrderItem")
                        .WithOne("LabResult")
                        .HasForeignKey("KayCare.Core.Entities.LabResult", "LabOrderItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KayCare.Core.Entities.User", "OrderingDoctor")
                        .WithMany()
                        .HasForeignKey("OrderingDoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabOrderItem");

                    b.Navigation("OrderingDoctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PatientAllergy", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PatientDocument", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Payment", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("ReceivedBy");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Prescription", b =>
                {
                    b.HasOne("KayCare.Core.Entities.User", "DispensedBy")
                        .WithMany()
                        .HasForeignKey("DispensedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KayCare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.User", "PrescribedBy")
                        .WithMany()
                        .HasForeignKey("PrescribedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispensedBy");

                    b.Navigation("Patient");

                    b.Navigation("PrescribedBy");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionTemplate", b =>
                {
                    b.HasOne("KayCare.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionTemplateItem", b =>
                {
                    b.HasOne("KayCare.Core.Entities.PrescriptionTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KayCare.Core.Entities.User", b =>
                {
                    b.HasOne("KayCare.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KayCare.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("KayCare.Core.Entities.DispenseEvent", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabOrderItem", b =>
                {
                    b.Navigation("LabResult");
                });

            modelBuilder.Entity("KayCare.Core.Entities.LabResult", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Patient", b =>
                {
                    b.Navigation("Allergies");
                });

            modelBuilder.Entity("KayCare.Core.Entities.Prescription", b =>
                {
                    b.Navigation("DispenseEvents");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("KayCare.Core.Entities.PrescriptionTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
